helm update lavanya -14

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -69,7 +69,24 @@ jobs:
               --namespace default \
               --set image.repository=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }} \
               --set image.tag=${{ steps.vars.outputs.sha_short }}
-            
+
+  cleanup-eks:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+          aws-secret-access-key: ${{ secrets.AWS_SCERET_KEY }}
+          aws-region: ap-south-1
+
+      - name: Update Kubeconfig
+        run: aws eks update-kubeconfig --region ap-south-1 --name my_cluster
+
+      - name: Uninstall Helm Release
+        run: |
+          # The '|| true' ensures the workflow doesn't fail if the release is already deleted
+          helm uninstall my-app-release --namespace default || true
             
 
 
